controller_manager:
  ros__parameters:

    update_rate: 50  # Fréquence de calcul en Hz
    use_sim_time: true

    # Lecture de l'état réel des 4 roues
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Contrôleur de mouvement Skid-Steering / DiffDrive
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    use_sim_time: true

    # Association exacte avec les joints de ton URDF
    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']

    # Dimensions physiques tirées de tes variables Xacro
    wheel_separation: 0.297
    wheel_radius: 0.06

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Repères cinématiques
    base_frame_id: base_footprint
    odom_frame_id: odom
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # Empêche les conflits TF si tu as déjà un OdometryPublisher
    #enable_odom_tf: false
    use_stamped_vel: false


    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 60.0 # seconds
    publish_limited_velocity: true
    #velocity_rolling_window_size: 10.0

    # Saturated Control (Limites d'accélération et de vitesse)

    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 1.0
    #linear.x.min_velocity: .NAN
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 0.8

    # linear.x.max_deceleration: .NAN
    # linear.x.max_acceleration_reverse: .NAN
    # linear.x.max_deceleration_reverse: .NAN
    # linear.x.max_jerk: .NAN
    # linear.x.min_jerk: .NAN


    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 2.0
    #angular.z.min_velocity: .NAN

    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 1.5

    # angular.z.max_deceleration: .NAN
    # angular.z.max_acceleration_reverse: .NAN
    # angular.z.max_deceleration_reverse: .NAN
    # angular.z.max_jerk: .NAN
    # angular.z.min_jerk: .NAN


    # linear:
    #   x:
    #     has_velocity_limits: true
    #     max_velocity: 1.0
    #     has_acceleration_limits: true
    #     max_acceleration: 0.8
    # angular:
    #   z:
    #     has_velocity_limits: true
    #     max_velocity: 2.0
    #     has_acceleration_limits: true
    #     max_acceleration: 1.5

joint_broad:
  ros__parameters:
    use_sim_time: true